// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4pLeG-guvuLtbZaHDFTgt78SmhrM1F-Y',
    appId: '1:621202049424:web:fb5465f6a69b1b1d5e4b15',
    messagingSenderId: '621202049424',
    projectId: 'eshop-e85d8',
    authDomain: 'eshop-e85d8.firebaseapp.com',
    storageBucket: 'eshop-e85d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtca7PunLE97aaXySf2gJoSqQOFwgsMA',
    appId: '1:621202049424:android:0a99677f2d175f3d5e4b15',
    messagingSenderId: '621202049424',
    projectId: 'eshop-e85d8',
    storageBucket: 'eshop-e85d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8IB4OqMe2NscY8wgRsoZo-UfBqojXLg',
    appId: '1:621202049424:ios:c1a90b5db79dc77f5e4b15',
    messagingSenderId: '621202049424',
    projectId: 'eshop-e85d8',
    storageBucket: 'eshop-e85d8.appspot.com',
    iosClientId: '621202049424-m6hb4p5eeicb9i1e63ei1e3bctdkhqpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN8IB4OqMe2NscY8wgRsoZo-UfBqojXLg',
    appId: '1:621202049424:ios:c1a90b5db79dc77f5e4b15',
    messagingSenderId: '621202049424',
    projectId: 'eshop-e85d8',
    storageBucket: 'eshop-e85d8.appspot.com',
    iosClientId: '621202049424-m6hb4p5eeicb9i1e63ei1e3bctdkhqpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopingapp',
  );
}
